"""Create db

Revision ID: edc9c882b29b
Revises: 650ceb31951f
Create Date: 2023-06-01 00:56:31.835735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc9c882b29b'
down_revision = '650ceb31951f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
